Sp 14/testing calender events modification
based-kwl/SemesterPlanner-client pull request #94
Opened 2022-11-29 22:21 UTC by guaj

Fixed Sp-14 branch + e2e tests

2022-11-30 17:08 UTC, mnashat reviewed
One small change (check comment), but great job otherwise!

2022-11-30 17:38 UTC, mnashat requested changes
Requested a few changes, great job otherwise!

2022-11-30 17:38 UTC, mnashat commented on src/components/Calendar/Event/EditEvent.js
> +    const [eventError, seteventError] = React.useState({ message: "Error, please try again later", hasError: false });
Should be `setEventError` for naming conventions.

2022-11-30 17:38 UTC, mnashat commented on src/components/Calendar/Calendar.js
> +    const [eventError, seteventError] = React.useState({ message: "Error, please try again later", hasError: false });
What is the use of `eventError` state in this file? It is being set, but not used to display errors to the user (or anything else). Please remove this state if it's not being used.

2022-11-30 18:01 UTC, kikkiii21 commented on src/components/Calendar/Event/EditEvent.js
> +        console.log("calling .get inside fetchData()")
remove console.log

2022-11-30 18:01 UTC, kikkiii21 commented on src/components/Calendar/Event/EditEvent.js
> +                console.log(res)
remove console.log

2022-11-30 18:01 UTC, kikkiii21 commented on src/components/Calendar/Event/EditEvent.js
> +                console.log(err)
remove console.log

2022-11-30 18:01 UTC, kikkiii21 commented on src/components/Calendar/Event/EditEvent.js
> +        console.log("Calling fetchData()")
remove console.log

2022-11-30 18:02 UTC, kikkiii21 commented on src/components/Calendar/Event/EditEvent.js
> +        console.log(eventData)
remove console.log

2022-11-30 18:04 UTC, kikkiii21 commented on src/components/FriendList/FriendSearch.js
> +                                            console.log(res.data.email);
remove console.log

2022-11-30 18:40 UTC, guaj commented on cypress/support/friends.js
> +    cy.get('[data-test="Friends List"]').click();
yes

2022-11-30 19:17 UTC, c0rnkrump3t approved these changes

2022-12-01 01:28 UTC, based-kwl requested changes
Some minor issues with the e2e testing, otherwise good job.

2022-12-01 01:28 UTC, based-kwl commented on cypress/e2e/friends.cy.js
> +        cy.get(`[data-test="delete-friend-${Cypress.env('email1')}"]`).click();
This test also sends duplicate requests, but are not caught by the BE and remain valid.

2022-12-01 01:28 UTC, based-kwl commented on cypress/e2e/friends.cy.js
> +        cy.cancelRequest(Cypress.env('email1'));
This test sends a duplicate request.

2022-12-01 01:37 UTC, based-kwl requested changes

2022-12-01 01:37 UTC, based-kwl commented on src/components/FriendList/FriendsNotification.js
>          axios.post(`${process.env.REACT_APP_BASE_URL}friend/cancel-request`,{requestId:id})
include the email in the request as `email`

2022-12-03 01:48 UTC, guaj commented
Last test result : 
<img width="653" alt="image" src="https://user-images.githubusercontent.com/60197474/205416741-2bf73406-0b6f-40db-85d3-6d00836b596c.png">

2022-12-03 01:51 UTC, based-kwl approved these changes

2022-12-03 02:53 UTC, mnashat commented on src/components/Calendar/Event/EditEvent.js
>              <UpdateCancelButton backgroundColor={'#C8C8C8'} content="Cancel" onClick={() => { handleEvent() }} />
Why does the cancel button call handleEvent()? It should not make a post request to the database.

2022-12-04 13:46 UTC, mnashat approved these changes

2022-12-04 22:48 UTC, kikkiii21 approved these changes

2022-12-04 22:48 UTC, kikkiii21 commented on src/components/Calendar/Calendar.js
> +    const [academicEvents, setAcedemicEvents] = useState([]);
there's a typo, it should be setAcademic not setAcedemic

2022-12-04 22:59 UTC, merged