Sp 92 UI
based-kwl/SemesterPlanner-client pull request #97
Opened 2022-12-16 17:52 UTC by c0rnkrump3t

2022-12-16 19:00 UTC, guaj requested changes

2022-12-16 19:01 UTC, guaj commented on src/components/Calendar/Event/EventDetails.js
> +                                    <CalendarTextField
also create event has duplicates. You can create an eventForm in the custom mui components and call this form from all 3 components. Will reduce code duplication a lot. Also will be easier to test / maintain

2022-12-16 19:04 UTC, guaj commented
Also do not forget to post the screenshot of the npm run e2e results.
That way we make sure that you did not break any feature.

2022-12-20 00:17 UTC, c0rnkrump3t commented on src/components/Calendar/Event/EventDetails.js
> +                                    <CalendarTextField
![image](https://user-images.githubusercontent.com/61073494/208552431-7845203a-e203-4e1a-be99-6dd47cbf6bd0.png)
![image](https://user-images.githubusercontent.com/61073494/208552528-c354973e-9630-4a98-a2fd-f0fa72f72fe0.png)

2022-12-21 04:12 UTC, guaj approved these changes

2022-12-29 04:09 UTC, mnashat requested changes
- For the event details page shown below:
![image](https://user-images.githubusercontent.com/72574688/209901446-68e19cbd-477c-4ec1-a2aa-877ae2dae6d0.png)
, it would be better if you edited your `Starting date` formatting to only show the date (i.e. remove 'T00:30:57.000Z' from the display).

- For the drawer shown below:
![image](https://user-images.githubusercontent.com/72574688/209901606-dfc8757d-6e38-4de1-b93d-a26e9fc29fe9.png)
, this becomes redundant when we also have an event details page. We should either have a drawer for the events on the calendar page or the event details page, not both.

- The delete functionality does not work. This is a backend issue, however, so @guaj please fix. The issue is with variable names. In the `deleteOne(...)` method in the EventRepository shown below: 
![image](https://user-images.githubusercontent.com/72574688/209901906-553de5fe-d689-4f0a-b0cd-97115b96c1eb.png)
, `eventID: eventID.toString()` should be `_id: eventID.toString()` since we removed the eventID field from the tables.

- You are using `SP-14/Refactor-Calendar-Events` backend branch. However, this branch seems to already be merged into `main`, yet the event details page does not load properly using the `main` backend branch. This warrants further investigation, as compatibility with the `main` backend branch is broken.

Note that I haven't reviewed the code itself, as there is some work to be done. I will review the code once everything is properly integrated.

2023-01-11 18:50 UTC, mnashat approved these changes

2023-01-11 20:14 UTC, merged